### ISSUE TITLE
Add 'enumValues { name description }' to include parameter meta information to dg_call() return data frame

### ISSUE THREAD

**Issue by lhehnke** [CorrelAid/datenguideR#8]
Required to tell the values for the respective parameters apart in the dg_call() output. See the current discussion in our Slack channel for more infos.

**Comment by favstats** [comment]
Alrighty, so this commit should essentially implement what we care about. Rather than making an API call to get the additional info about the params, I just merged the data from `dg_meta`. It's a bit inelegant at the moment so it could potentially be made better in the future.

https://github.com/CorrelAid/datenguideR/commit/99251aa46bf03303d45e3f984ba91ccd10447e64
